using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using ITX.Application.Interfaces;
//using ITX.Application
using ITX.Application.Interfaces.FormYonetim;
using ITX.Application.Interfaces.Identity;
using ITX.Application.Interfaces.Test;
using ITX.Application.Interfaces.Predefined;
using ITX.Infrastructure.Data.Services.FormYonetim;
using ITX.Infrastructure.Data.Services.Identity;
//using ITX.Infrastructure
using ITX.Infrastructure.Data.Services.Test;
using ITX.Infrastructure.Data.Services.Predefined;
using ITX.Infrastructure.Services;
using ITX.Infrastructure.Helpers;

namespace ITX.Infrastructure
{
    public static class ConfigureServices
    {
        public static IServiceCollection AddInfrastructureServices(
            this IServiceCollection services,
            IConfiguration configuration)
        {
            services.AddScoped<IMenuService, MenuService>();
            services.AddScoped<IRoleService, RoleService>();
            services.AddScoped<IUserService, UserService>();

            services.AddScoped<IFormTanimService, FormTanimService>();
            services.AddScoped<IFormAlanService, FormAlanService>();
            services.AddScoped<IFormDegerService, FormDegerService>();
            services.AddScoped<IValueTextService, ValueTextService>();
            services.AddScoped<IValueNumberService, ValueNumberService>();
            services.AddScoped<IDegerTarihService, DegerTarihService>();

            services.AddScoped<IEnumVeriService, EnumVeriService>();
            services.AddScoped<ICurrencyDefinitionService, CurrencyDefinitionService>();
            services.AddScoped<IDistrictService, DistrictService>();
            services.AddScoped<ICountryService, CountryService>();
            services.AddScoped<ICityService, CityService>();
            services.AddScoped<IAppSettingService, AppSettingService>();
            services.AddScoped<IAnnounceService, AnnounceService>();
            services.AddScoped<IUserClaimService, UserClaimService>();
            services.AddScoped<IRoleClaimService, RoleClaimService>();

            services.AddTransient<ICurrentUserService, CurrentUserService>();
            services.AddTransient<IDateTime, DateTimeService>();
            services.AddTransient<IFileStorage, FileStorage>();
            services.AddTransient<IRequestLogService, RequestLogService>();
            services.AddTransient<IAuditLogService, AuditLogService>();
            services.AddTransient<LogResponse>();

            /* <auto-generated (for-script)/> */  //Bu satir onemlidir script icin lazim VERY IMPORTANT !! !!
            services.AddScoped<ILessonService, LessonService>();

			services.AddScoped<IStudentLessonService, StudentLessonService>();

			services.AddScoped<IStudentService, StudentService>();

			services.AddScoped<IScenarioService, ScenarioService>();

			services.AddScoped<IClaimTypeService, ClaimTypeService>();


            return services;
        }
    }
}
