using Ardalis.Result;
using ITX.Application;
using ITX.Application.Dtos.Predefined;
using ITX.Application.Interfaces.Predefined;
using ITX.Application.ViewModels;
using ITX.Infrastructure.Tools;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ITX.WebAPI.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class PredefinedController : BaseController
    {
        private readonly ICurrencyDefinitionService _currencyDefinitionService;
        private readonly ICountryService _countryService;
        private readonly ICityService _cityService;
        private readonly IDistrictService _districtService;
        private readonly IAppSettingService _appSettingService;
        private readonly IAnnounceService _announceService;

        public PredefinedController(
            ICurrencyDefinitionService CurrencyDefinitionService,
            ICountryService countryService, ICityService cityService,
            IDistrictService districtService,
            IAppSettingService appSettingService,
           IAnnounceService announceService
            )
        {
            _currencyDefinitionService = CurrencyDefinitionService;
            _countryService = countryService;
            _cityService = cityService;
            _districtService = districtService;
            _appSettingService = appSettingService;
            _announceService = announceService;
        }

        [HttpPost("LoadDataTable/{FType}/{UstId?}")]
        public async Task<Result<JsonResult>> LoadDataTable(string FType, long? UstId)
        {
            var vm = new DataTableViewModel(Request);
            vm.UstId = UstId;

            return FType switch
            {
                /* <auto-generated (for-script-LoadDataTable)/> */
                "CurrencyDefinition" => await _currencyDefinitionService.LoadDataTableAsync(vm),
                "Country" => await _countryService.LoadDataTableAsync(vm),
                "City" => await _cityService.LoadDataTableAsync(vm),
                "District" => await _districtService.LoadDataTableAsync(vm),
                "AppSetting" => await _appSettingService.LoadDataTableAsync(vm),
                "Announce" => await _announceService.LoadDataTableAsync(vm),
                _ => null
            };
        }


        [HttpGet("Get/{FType}/{id}")]
        public async Task<Result<Object>> Get(string FType, long id)
        {
            return FType switch
            {
                /* <auto-generated (for-script-Get)/> */
                "CurrencyDefinition" => (await _currencyDefinitionService.GetAsync(predicate: x => x.Id == id)).Value,
                "Country" => (await _countryService.GetAsync(x => x.Id == id)).Value,
                "City" => (await _cityService.GetAsync(x => x.Id == id)).Value,
                "District" => (await _districtService.GetAsync(x => x.Id == id)).Value,
                "AppSetting" => (await _appSettingService.GetAsync(x => x.Id == id)).Value,
                "Announce" => (await _announceService.GetAsync(x => x.Id == id)).Value,
                _ => null
            };
        }

        [HttpGet("GetAll/{FType}/{UstId?}")]
        public async Task<Result<Object>> GetAll(string FType, long? UstId)
        {
            return FType switch
            {
                /* <auto-generated (for-script-GetAll)/> */
                "CurrencyDefinition" => (await _currencyDefinitionService.GetAllAsync()).Value,
                "Country" => (await _countryService.GetAllAsync()).Value,
                "City" => (await _cityService.GetAllAsync(predicate: UstId.HasValue ? x => x.CountryId == UstId : null)).Value,
                "District" => (await _districtService.GetAllAsync()).Value,
                "AppSetting" => (await _appSettingService.GetAllAsync()).Value,
                "Announce" => (await _announceService.GetAllAsync()).Value,
                _ => null
            };
        }

        [HttpDelete("Delete/{FType}/{id}")]
        public async Task<Result<Object>> Delete(string FType, long id)
        {
            switch (FType)
            {
                /* <auto-generated (for-script-Delete)/> */
                case "CurrencyDefinition":
                    {
                        await _currencyDefinitionService.DeleteAsync(predicate: x => x.Id == id);
                        return Result<Object>.Success(new { deleted = true });
                    }
                case "Country":
                    {
                        await _countryService.DeleteAsync(x => x.Id == id);
                        return Result<Object>.Success(new { deleted = true });
                    }
                case "City":
                    {
                        await _cityService.DeleteAsync(x => x.Id == id);
                        return Result<Object>.Success(new { deleted = true });
                    }
                case "District":
                    {
                        await _districtService.DeleteAsync(x => x.Id == id);
                        return Result<Object>.Success(new { deleted = true });
                    }
                case "AppSetting":
                    {
                        await _appSettingService.DeleteAsync(x => x.Id == id);
                        return Result<Object>.Success(new { deleted = true });
                    }
                case "Announce":
                    {
                        await _announceService.DeleteAsync(x => x.Id == id);
                        return Result<Object>.Success(new { deleted = true });
                    }
                default:
                    return null;
            }
        }

        /* <auto-generated (for-script-Save)/> */
        [HttpPost("SaveCurrencyDefinition")]
        public async Task<Result<CurrencyDefinitionDto>> SaveCurrencyDefinition([FromForm] CurrencyDefinitionDto dto)
        {
            try
            {
                Result<CurrencyDefinitionDto> result;
                if (dto.Id == 0)
                {
                    result = await _currencyDefinitionService.AddAsync(dto);
                }
                else
                {
                    result = await _currencyDefinitionService.UpdateAsync(dto);
                }

                return result.Status switch
                {
                    ResultStatus.Ok => Result<CurrencyDefinitionDto>.Success(result.Value),
                    ResultStatus.Error => Result<CurrencyDefinitionDto>.Error(),
                    ResultStatus.Forbidden => Result<CurrencyDefinitionDto>.Forbidden(),
                    ResultStatus.Invalid => Result<CurrencyDefinitionDto>.Invalid(result.ValidationErrors.Select(error => new ValidationError() { Identifier = error.Identifier, ErrorMessage = error.ErrorMessage }).ToList()),
                    ResultStatus.NotFound => Result<CurrencyDefinitionDto>.NotFound(),
                    _ => null
                };
            }
            catch (Exception ex)
            {
                return Result<CurrencyDefinitionDto>.Error(ex.Message);
            }
        }

        [HttpPost("SaveCountry")]
        public async Task<Result<CountryDto>> SaveCountry([FromForm] CountryDto dto)
        {
            try
            {
                Result<CountryDto> result;
                if (dto.Id == 0)
                {
                    result = await _countryService.AddAsync(dto);
                }

                else
                {
                    result = await _countryService.UpdateAsync(dto);
                }

                return result.Status switch
                {
                    ResultStatus.Ok => Result<CountryDto>.Success(result.Value),
                    ResultStatus.Error => Result<CountryDto>.Error(),
                    ResultStatus.Forbidden => Result<CountryDto>.Forbidden(),
                    ResultStatus.Invalid => Result<CountryDto>.Invalid(result.ValidationErrors.Select(error => new ValidationError() { Identifier = error.Identifier, ErrorMessage = error.ErrorMessage }).ToList()),
                    ResultStatus.NotFound => Result<CountryDto>.NotFound(),
                    _ => null
                };
            }
            catch (Exception ex)
            {
                return Result<CountryDto>.Error(ex.Message);
            }
        }

        [HttpPost("SaveCity")]
        public async Task<Result<CityDto>> SaveCity([FromForm] CityDto dto)
        {
            try
            {
                Result<CityDto> result;
                if (dto.Id == 0)
                    result = await _cityService.AddAsync(dto);

                else
                    result = await _cityService.UpdateAsync(dto);

                return result.Status switch
                {
                    ResultStatus.Ok => Result<CityDto>.Success(result.Value),
                    ResultStatus.Error => Result<CityDto>.Error(),
                    ResultStatus.Forbidden => Result<CityDto>.Forbidden(),
                    ResultStatus.Invalid => Result<CityDto>.Invalid(result.ValidationErrors.Select(error => new ValidationError() { Identifier = error.Identifier, ErrorMessage = error.ErrorMessage }).ToList()),
                    ResultStatus.NotFound => Result<CityDto>.NotFound(),
                    _ => null
                };
            }
            catch (Exception ex)
            {
                return Result<CityDto>.Error(ex.Message);
            }
        }

        [HttpPost("SaveDistrict")]
        public async Task<Result<DistrictDto>> SaveDistrict([FromForm] DistrictDto dto)
        {
            try
            {
                Result<DistrictDto> result;
                if (dto.Id == 0)
                {
                    result = await _districtService.AddAsync(dto);
                }

                else
                {
                    result = await _districtService.UpdateAsync(dto);
                }

                return result.Status switch
                {
                    ResultStatus.Ok => Result<DistrictDto>.Success(result.Value),
                    ResultStatus.Error => Result<DistrictDto>.Error(),
                    ResultStatus.Forbidden => Result<DistrictDto>.Forbidden(),
                    ResultStatus.Invalid => Result<DistrictDto>.Invalid(result.ValidationErrors.Select(error => new ValidationError() { Identifier = error.Identifier, ErrorMessage = error.ErrorMessage }).ToList()),
                    ResultStatus.NotFound => Result<DistrictDto>.NotFound(),
                    _ => null
                };
            }
            catch (Exception ex)
            {
                return Result<DistrictDto>.Error(ex.Message);
            }
        }

        [HttpPost("SaveAppSetting")]
        public async Task<Result<AppSettingDto>> SaveAppSetting([FromForm] AppSettingDto dto)
        {
            try
            {
                Result<AppSettingDto> result;
                if (dto.Id == 0)
                {
                    result = await _appSettingService.AddAsync(dto);
                }

                else
                {
                    result = await _appSettingService.UpdateAsync(dto);
                    var eski = ApplicationData.ApplicationSettings.Where(x => x.Ad == dto.Ad).FirstOrDefault();
                    eski = result.Value;
                }

                return result.Status switch
                {
                    ResultStatus.Ok => Result<AppSettingDto>.Success(result.Value),
                    ResultStatus.Error => Result<AppSettingDto>.Error(),
                    ResultStatus.Forbidden => Result<AppSettingDto>.Forbidden(),
                    ResultStatus.Invalid => Result<AppSettingDto>.Invalid(result.ValidationErrors.Select(error => new ValidationError() { Identifier = error.Identifier, ErrorMessage = error.ErrorMessage }).ToList()),
                    ResultStatus.NotFound => Result<AppSettingDto>.NotFound(),
                    _ => null
                };
            }
            catch (Exception ex)
            {
                return Result<AppSettingDto>.Error(ex.Message);
            }
        }

        [HttpPost("SaveAnnounce")]
        public async Task<Result<AnnounceDto>> SaveAnnounce([FromForm] AnnounceDto dto)
        {
            try
            {
                Result<AnnounceDto> result;
                if (dto.Id == 0)
                {
                    result = await _announceService.AddAsync(dto);
                }

                else
                {
                    result = await _announceService.UpdateAsync(dto);
                }

                return result.Status switch
                {
                    ResultStatus.Ok => Result<AnnounceDto>.Success(result.Value),
                    ResultStatus.Error => Result<AnnounceDto>.Error(),
                    ResultStatus.Forbidden => Result<AnnounceDto>.Forbidden(),
                    ResultStatus.Invalid => Result<AnnounceDto>.Invalid(result.ValidationErrors),
                    ResultStatus.NotFound => Result<AnnounceDto>.NotFound(),
                    _ => null
                };
            }
            catch (Exception ex)
            {
                return Result<AnnounceDto>.Error(ex.Message);
            }
        }

        [HttpPost("Sifrele")]
        public async Task<Result<string>> Sifrele([FromForm] string sText)
        {
            return Result<string>.Success(Functions.Encrypt(sText));
        }

        [HttpPut("ToggleIsPublish/{id}")]
        public async Task<Result<bool>> ToggleIsActive(int id)
        {
            var announceDto = await _announceService.GetAsync(x => x.Id == id);
            if (!announceDto.IsSuccess)
            {
                return Result<bool>.Error();
            }

            announceDto.Value.IsPublish = !announceDto.Value.IsPublish;

            var result = await _announceService.UpdateAsync(announceDto);

            return result.Status switch
            {
                ResultStatus.Ok => Result<bool>.Success(result.Value.IsPublish),
                ResultStatus.Error => Result<bool>.Error(),
                ResultStatus.Forbidden => Result<bool>.Forbidden(),
                ResultStatus.Invalid => Result<bool>.Invalid(result.ValidationErrors),
                ResultStatus.NotFound => Result<bool>.NotFound(),
                _ => null
            };
        }

        [HttpGet("GetEntityData/{formName}/{id}")]
        public async Task<Result<string>> GetEntityData(string formName, long id) => Result.Success(await _appSettingService.GetEntityData(formName, id));

        [HttpGet("GetListForMap")]
        public async Task<Result<Dictionary<string, object>>> GetListForMap()
        {
            try
            {
                var result = await _cityService.GetAllAsync(x => x.PhoneCode != null);

                Dictionary<string, object> keyValuePairs = new Dictionary<string, object>();
                if (result.IsSuccess)
                {
                    keyValuePairs = result.Value.DistinctBy(x => x.Name).ToDictionary(p => p.Name, x => (object)new
                    {
                        Id = x.Id,
                        PhoneCode = x.PhoneCode,
                    });
                }

                return Result<Dictionary<string, object>>.Success(keyValuePairs, "Düzenleme Ýþlemi Baþarýlý!");
            }
            catch (Exception ex)
            {
                return Result<Dictionary<string, object>>.Error("Düzenleme Ýþlemi Baþarýsýz!");
            }
        }
    }
}






