name: .NET Core CI/CD for Multiple Projects

on:
  push:
    branches: [ webapi-deployment ]
  workflow_dispatch:

jobs:
  build_and_deploy_api:
    runs-on: ubuntu-latest
    name: Build and Deploy WebAPI
    steps:
      - uses: actions/checkout@v2

      - name: Cache NuGet Packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/YourSolution.sln', '**/NuGet.config') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET Core for WebAPI
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '8.0.x'

      - name: Build WebAPI
        run: dotnet build ./src/WebAPI/ITX.WebAPI.csproj

      - name: Publish WebAPI
        run: dotnet publish ./src/WebAPI/ITX.WebAPI.csproj -c Release -o out/WebAPI

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: ignore

      - name: Zip the build files
        run: tar -czvf WebAPI.tar.gz -C out/WebAPI .

      - name: Deploy
        run: scp WebAPI.tar.gz ${{ vars.USER_NAME }}@${{ secrets.SSH_HOST }}:${{ vars.WORK_DIR }}

      - name: Extract on server
        run: ssh ${{ vars.USER_NAME }}@${{ secrets.SSH_HOST }} "tar -xzvf ${{vars.WORK_DIR }}/WebAPI.tar.gz -C ${{ vars.WORK_DIR }} && rm ${{ vars.WORK_DIR }}/WebAPI.tar.gz"
      
      - name: Restart WebAPI Service
        run: ssh ${{ vars.USER_NAME }}@${{ secrets.SSH_HOST }} "sudo systemctl restart webapi.service"

      - name: Restart Nginx Service
        run: ssh ${{ vars.USER_NAME }}@${{ secrets.SSH_HOST }} "sudo systemctl restart nginx"

