name: .NET Core CI/CD for Multiple Projects

on:
  push:
    branches: [ webmvc-deployment ]
  workflow_dispatch:

jobs:
  build_and_deploy_mvc:
    runs-on: ubuntu-latest
    name: Build and Deploy WebMVC
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core for WebAPI
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '8.0.x'

      - name: Restore for WebMVC
        run: dotnet restore ./src/WebMVC/ITX.WebMVC.csproj

      - name: Build WebMVC
        run: dotnet build ./src/WebMVC/ITX.WebMVC.csproj --no-restore
      - name: Publish WebMVC
        run: dotnet publish ./src/WebMVC/ITX.WebMVC.csproj -c Release -o out/WebMVC

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            known_hosts: ${{ secrets.KNOWN_HOSTS }}
            if_key_exists: ignore

      - name: Deploy
        run: scp -r out/WebMVC ${{ vars.USER_NAME }}@${{ secrets.SSH_HOST }}:${{ vars.WORK_DIR }}

      - name: Restart WebMVC Service
        run: ssh ${{ vars.USER_NAME }}@${{ secrets.SSH_HOST }} "sudo systemctl restart webmvc.service"
        
      - name: Restart Nginx Service
        run: ssh ${{ vars.USER_NAME }}@${{ secrets.SSH_HOST }} "sudo systemctl restart nginx"