name: .NET Core CI/CD for Multiple Projects

on:
  push:
    branches: [ webmvc-deployment ]
  workflow_dispatch:

jobs:
  build_and_deploy_mvc:
    runs-on: ubuntu-latest
    name: Build and Deploy WebMVC
    steps:
      - uses: actions/checkout@v2

      - name: Cache NuGet Packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/YourSolution.sln', '**/NuGet.config') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
              
      - name: Setup .NET Core for WebAPI
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '8.0.x'

      - name: Build WebMVC
        run: dotnet build ./src/WebMVC/ITX.WebMVC.csproj
      - name: Publish WebMVC
        run: dotnet publish ./src/WebMVC/ITX.WebMVC.csproj -c Release -o out/WebMVC

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            known_hosts: ${{ secrets.KNOWN_HOSTS }}
            if_key_exists: ignore

      - name: Zip the build files
        run: tar -czvf WebMVC.tar.gz -C out/WebMVC .
      
      - name: Deploy
        run: scp WebMVC.tar.gz ${{ vars.USER_NAME }}@${{ secrets.SSH_HOST }}:${{ vars.WORK_DIR }}

      - name: Extract on server
        run: ssh ${{ vars.USER_NAME }}@${{ secrets.SSH_HOST }} "tar -xzvf ${{vars.WORK_DIR }}/WebMVC.tar.gz -C ${{ vars.WORK_DIR }}/WebMVC/ && rm ${{ vars.WORK_DIR }}/WebMVC.tar.gz"
      
      - name: Restart WebMVC Service
        run: ssh ${{ vars.USER_NAME }}@${{ secrets.SSH_HOST }} "sudo systemctl restart webmvc.service"
        
      - name: Restart Nginx Service
        run: ssh ${{ vars.USER_NAME }}@${{ secrets.SSH_HOST }} "sudo systemctl restart nginx"
        