function Add-DBSet () {
    $EntityName=$requiredInfo.EntityName
    $Namespace=$requiredInfo.Namespace

    $pathName = "././Persistance/Database/Context/ITManagementDbContext.cs"
    $file = Get-Content $pathName
    $usingDomain = "using ITX.Domain.Entities.$($Namespace)"
    $newString =""
    if (!(([string]$file).Contains("public virtual DbSet<$($EntityName)> $($EntityName)s { get; set; }") -or ([string]$file).Contains("public DbSet<$($EntityName)> $($EntityName) { get; set; }"))) {
        $dbSetLine = "`t`tpublic virtual DbSet<$($EntityName)> $($EntityName)s { get; set; }"
        foreach ($line in $file) {
            if ($line.Contains("/* <auto-generated (for-script)/> */")) {
                $line += "`n" + $dbSetLine + "`n"
            }
            elseif ($line.Contains("// using ITX.Domain")) {
                if (!([string]$file).Contains($usingDomain)) {
                    $line += "`n" + "using ITX.Domain.Entities.$($Namespace);"
                }
            }
            $newString += $line + "`n";
        }
        New-Item -Path $pathName -Value $newString -Force
    }
    else {
        Write-Host "`t¬ Context'de zaten mevcut." -ForegroundColor  DarkBlue
    }
}